---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-test-606-hdu-io-v1-microdev
  failurePolicy: Fail
  name: mmicrodev.kb.io
  rules:
  - apiGroups:
    - test.606.hdu.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - microdevs
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-test-606-hdu-io-v1-microdev
  failurePolicy: Fail
  name: vmicrodev.kb.io
  rules:
  - apiGroups:
    - test.606.hdu.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - microdevs
  sideEffects: None
